name: CDK Deploy Day
run-name: Deploy ${{ inputs.environment }} to AWS ${{ inputs.region }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options: [ 'poc', 'dev', 'qa', 'prod' ]
        default: 'poc'
      region:
        description: 'Deployment region'
        required: true
        default: 'eu-north-1'
      day:
        description: 'Deployment day'
        required: true
        type: choice
        options: [ 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun' ]
      bootstrap:
        description: 'Run CDK bootstrap?'
        type: boolean
        required: false
        default: 'false'

defaults:
  run:
    shell: bash
    working-directory: ./cdk-demo-deployday

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CDK_DEPLOYMENT_DAY: ${{ inputs.day }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build CDK App
        run: npm run build

      - name: Configure AWS credentials via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}

      - name: Bootstrap CDK (optional)
        if: ${{ inputs.bootstrap == true }}
        run: npx cdk bootstrap

      - name: Synthesize all CDK Stacks
        run: npx cdk synth --all --quiet

      - name: Run CDK tests (optional)
        if: ${{ inputs.tests == true }}
        run: npm run test

      - name: List CDK Stacks
        run: npx cdk list --long

      - name: Deploy all CDK Stacks
        run: npx cdk deploy --all --ci --progress bar --ignore-no-stacks --require-approval never

      - name: Compare all CDK Stacks
        run: npx cdk diff --all
