name: SST Astro Site
run-name: Deploy ${{ inputs.stage }} to AWS ${{ inputs.region }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        type: choice
        options: [ 'poc', 'dev', 'qa', 'prod' ]
        default: 'poc'
      region:
        description: 'Deployment region'
        required: true
        default: 'eu-north-1'

defaults:
  run:
    shell: bash
    working-directory: ./sst-demo-astrosite

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build SST Application
        run: npm run build

      - name: Configure AWS credentials via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}

      - name: Deploy SST Application
        run: npx sst deploy --stage ${{ inputs.stage }} 
